--Создаём таблицы в БД CarService
USE CarService;

CREATE TABLE Employee (
	EmployeeID INT PRIMARY KEY IDENTITY(1,1),
	FullName VARCHAR(255) NOT NULL,
	Position VARCHAR(255) NOT NULL,
	);

CREATE TABLE Orders (
	OrderID INT PRIMARY KEY IDENTITY(1,1),
	OrderDate DATE NOT NULL,
	Executor VARCHAR(255) NOT NULL,
	Client VARCHAR(255) NOT NULL,
	ServiceName VARCHAR (255) NOT NULL,
	StatusDate DATE NOT NULL,
	StatusName VARCHAR(255) NOT NULL,
	Cost INT NOT NULL
	);

CREATE TABLE Client (
	ClientID INT PRIMARY KEY IDENTITY(1,1),
	FullName VARCHAR(255) NOT NULL,
	ClientCar VARCHAR(255) NOT NULL,
	PhoneNumber INT NOT NULL,
	Email VARCHAR(255) NOT NULL
	);


	--Почему нельзя назвать просто Service???
CREATE TABLE CarService (
	ServiceID INT PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(255) NOT NULL,
	[Type] VARCHAR(255) NOT NULL,
	Category VARCHAR(255) NOT NULL,
	Price INT NOT NULL
	);

CREATE TABLE Status (
	StatusID INT PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(255) NOT NULL
	);

CREATE TABLE SparePart (
	PartID INT PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(255) NOT NULL,
	PartBrand VARCHAR(255) NOT NULL,
	PartModel VARCHAR(255) NOT NULL,
	VendorCode INT NOT NULL,
	Availability VARCHAR(255) NOT NULL,
	Price INT NOT NULL,
	Quantity INT NOT NULL,
	Characters VARCHAR(255) NOT NULL,
	CompatibleCar VARCHAR(255) NOT NULL,
	);

CREATE TABLE Car (
	CarID INT PRIMARY KEY IDENTITY(1,1),
	Owner VARCHAR(255) NOT NULL,
	CarBrand VARCHAR(255) NOT NULL,
	CarModel VARCHAR(255) NOT NULL,
	RegNumber VARCHAR(255) NOT NULL,
	VIN VARCHAR(255) NOT NULL,
	YearOfManufacture DATE NOT NULL,
	Mileage INT NOT NULL,
	Engine VARCHAR(255) NOT NULL,
	Transmission VARCHAR(255) NOT NULL,
	Color VARCHAR(255) NOT NULL
	);

CREATE TABLE Color (
	ColorID INT PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(255) NOT NULL
	);

CREATE TABLE Engine (
	EngineID INT PRIMARY KEY IDENTITY(1,1),
	EngineNumber VARCHAR(255) NOT NULL,
	EnginePower INT NOT NULL,
	EngineCapacity FLOAT NOT NULL,
	);